import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./partial/header/header";
import Sidebar from "./partial/sidebar/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Header />

                <section className='dashboard-body account-body'>
                    <Sidebar />
                    {children}
                </section>
            </body>
        </html>
    );
}
